version: 1

formatters:
  standard:
    format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/app.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [ console, file_handler ]

loggers:
  genome_generator:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no
